spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barber_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: valen0428
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: mi-clave-secreta-super-segura-para-jwt-barberia
    expiration: 86400000
    
server:
  port: 8080